apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  namespace: minecraft
  labels:
    app: minecraft
spec:
  type: NodePort
  ports:
    - name: game-port
      protocol: TCP
      port: 25565
      nodePort: 30065
      targetPort: 25565
    - name: rcon-port
      protocol: TCP
      port: 25575
      nodePort: 30075
      targetPort: 25575
  selector:
    app: minecraft
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: surprise-automation/minecraft:1.17.1
        ports:
        - containerPort: 25565
        - containerPort: 25575
        resources:
          limits:
            memory: 15Gi
          requests:
            memory: 10Gi
        env:
          - name:  MC_MAX_RAM
            value: 15G
          - name:  MC_MIN_RAM
            value: 10G
      nodeSelector:
        nodetype: minecraft